services:
  db:
    image: postgres:16-alpine
    container_name: victoria-db
    environment:
      POSTGRES_USER: victoria
      POSTGRES_PASSWORD: victoria
      POSTGRES_DB: victoria
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U victoria"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: victoria-web
    environment:
      DATABASE_URL: postgresql://victoria:victoria@db:5432/victoria
      APP_NAME: IweKekeSare
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data:
